### ISSUE TITLE
Annotator must be able to detect name in example

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/nlp-sandbox-person-name-annotator-example#9]
![image](https://user-images.githubusercontent.com/3056480/95706282-4d8a1280-0c0b-11eb-97d4-9fade7a3f6b2.png)

**Comment by gkowalski** [comment]
I'm assuming that all changes to the openapi.yaml  including example documentation . I can create a PR that updates this with an example that covers DATE and Person examples.

**Comment by gkowalski** [comment]
This was also addressed  the latest PR . https://github.com/Sage-Bionetworks/nlp-sandbox-person-name-annotator-example/pull/12
